#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# sweep_mtp.sh — MTP=1,2,3,5 leak-probe sweep for the MRE bundle
#
# For each NUM_SPEC level, this script:
#   1. Writes a systemd user drop-in that sets NUM_SPEC=<level>
#   2. daemon-reload + restart vllm-qwen36-27b-sota.service
#   3. Waits for /v1/models to respond (max 5 min)
#   4. Runs the leak probe in BOTH modes (chat + tools)
#   5. Archives results under runs/mtp<level>/
#
# At the end, the drop-in is REMOVED so production returns to its baseline
# (NUM_SPEC=3 from the launcher default).
#
# Hardware: GPUs 0+1 only (TP=2). GPU 2 is reserved for gpt-oss-120b and is
# NEVER touched by this script — the launcher pins GPUs by UUID.
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ROOT="/tmp/qwen-bench-2026-05-12-v3-suite"
PROBE="${ROOT}/harness/leak_probe.py"
OUT_BASE="${ROOT}/mre/mtp-leak/runs"
DROPIN_DIR="${HOME}/.config/systemd/user/vllm-qwen36-27b-sota.service.d"
DROPIN_FILE="${DROPIN_DIR}/99-mre-sweep.conf"
SERVICE="vllm-qwen36-27b-sota.service"
ENDPOINT="http://localhost:11435/v1/chat/completions"
MODELS_URL="http://localhost:11435/v1/models"
MODEL="Qwen3.6-27B"

# Probe sizing — same across all 4 levels so the comparison is fair.
# Chat: 75 prompts × 3 repeats = 225 trials  (~3 min wall @ concurrency 4)
# Tools: 30 prompts × 2 repeats = 60 trials  (~1 min wall @ concurrency 4)
CHAT_N="${CHAT_N:-75}"
CHAT_REPEAT="${CHAT_REPEAT:-3}"
TOOLS_N="${TOOLS_N:-30}"
TOOLS_REPEAT="${TOOLS_REPEAT:-2}"
TEMPERATURE="${TEMPERATURE:-0.7}"
CONCURRENCY="${CONCURRENCY:-4}"
MAX_TOKENS_CHAT="${MAX_TOKENS_CHAT:-3000}"
MAX_TOKENS_TOOLS="${MAX_TOKENS_TOOLS:-4000}"

LEVELS=(${MTP_LEVELS:-1 2 3 5})

mkdir -p "${OUT_BASE}" "${DROPIN_DIR}"

ts() { date '+%Y-%m-%d %H:%M:%S'; }
log() { echo "[$(ts)] $*"; }

wait_ready() {
  local timeout=300
  local start=$(date +%s)
  while true; do
    if curl -fsS -m 5 "${MODELS_URL}" >/dev/null 2>&1; then
      log "  endpoint ready"
      return 0
    fi
    local now=$(date +%s)
    if (( now - start > timeout )); then
      log "  ERROR: endpoint not ready after ${timeout}s"
      return 1
    fi
    sleep 5
  done
}

set_mtp() {
  local n="$1"
  cat > "${DROPIN_FILE}" <<EOF
# Auto-generated by mre/mtp-leak/scripts/sweep_mtp.sh
# Temporary NUM_SPEC override for MTP leak sweep. Removed at end of sweep.
[Service]
Environment=NUM_SPEC=${n}
EOF
  systemctl --user daemon-reload
  log "  drop-in set NUM_SPEC=${n}; restarting service..."
  systemctl --user restart "${SERVICE}"
  wait_ready
}

restore_baseline() {
  log "Restoring production baseline (removing drop-in, NUM_SPEC=3 from launcher)..."
  rm -f "${DROPIN_FILE}"
  systemctl --user daemon-reload
  systemctl --user restart "${SERVICE}"
  wait_ready
  log "Production restored. Current NUM_SPEC = baseline (3)."
}

# Restore on any exit so production never lingers on a sweep value.
trap 'restore_baseline' EXIT

for level in "${LEVELS[@]}"; do
  log "═══════════════════════════════════════════════════════════════"
  log "MTP=${level} sweep starting"
  log "═══════════════════════════════════════════════════════════════"

  set_mtp "${level}"

  out_dir="${OUT_BASE}/mtp${level}"
  mkdir -p "${out_dir}"

  log "  chat probe: n=${CHAT_N} repeat=${CHAT_REPEAT} T=${TEMPERATURE}"
  python3 "${PROBE}" \
    --mode chat \
    --endpoint "${ENDPOINT}" \
    --model "${MODEL}" \
    --label "fp8-mtp${level}-chat" \
    --n "${CHAT_N}" --repeat "${CHAT_REPEAT}" \
    --temperature "${TEMPERATURE}" \
    --concurrency "${CONCURRENCY}" \
    --max-tokens "${MAX_TOKENS_CHAT}" \
    --out-dir "${out_dir}/chat" \
    2>&1 | tee "${out_dir}/chat.log"

  log "  tools probe: n=${TOOLS_N} repeat=${TOOLS_REPEAT} T=${TEMPERATURE}"
  python3 "${PROBE}" \
    --mode tools \
    --endpoint "${ENDPOINT}" \
    --model "${MODEL}" \
    --label "fp8-mtp${level}-tools" \
    --n "${TOOLS_N}" --repeat "${TOOLS_REPEAT}" \
    --temperature "${TEMPERATURE}" \
    --concurrency "${CONCURRENCY}" \
    --max-tokens "${MAX_TOKENS_TOOLS}" \
    --out-dir "${out_dir}/tools" \
    2>&1 | tee "${out_dir}/tools.log"

  log "MTP=${level} done. Leaks:"
  for mode in chat tools; do
    sjson="${out_dir}/${mode}/summary.json"
    if [ -f "$sjson" ]; then
      n_leaks=$(python3 -c "import json;d=json.load(open('$sjson'));print(d.get('n_leaks_total','?'))")
      n_trials=$(python3 -c "import json;d=json.load(open('$sjson'));print(d.get('n_trials',d.get('n_prompts','?')))")
      wall=$(python3 -c "import json;d=json.load(open('$sjson'));print(f\"{d.get('wall_s',0):.1f}\")")
      log "  ${mode}: ${n_leaks}/${n_trials} leaks (${wall}s)"
    fi
  done
done

log "═══════════════════════════════════════════════════════════════"
log "Sweep complete. Results under ${OUT_BASE}/"
log "═══════════════════════════════════════════════════════════════"
